# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  project: 'src/A-SIA2FrontendAngular'

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/A-SIA2FrontendAngular
    - pipelines

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    cd $(project)
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    cd $(project)
    ng build --prod
  displayName: 'ng build'

- script: |
    cd $(project)
    ng test --watch=false --karma-config karma.conf.ci.js --code-coverage
  displayName: 'ng test'
